id = "vrchat-api"
name = "VRChat API Proxy"
version = "0.1.0"
license = "MIT"
description = "K-API - VRChat API Proxy: FastAPI app for VRChat token & user/group data."

[[maintainers]]
name = "Kryscau"
email = "kryscau@kvs.fyi"

[requirements]
python = ">=3.8"

[services]
vrchat-api = { description = "VRChat API Proxy FastAPI service", systemd = true, port = 8000, app_port = 8000 }

[config]
domain = { description = "Domain to use for this app", required = true }

[arguments]
  [arguments.install]
  token = { description = "Security token to fetch your VRChat account.json", required = true }
  domain = { description = "Domain where the app will be accessible", required = true }

[metadata]
  ynh_app_version_format = "semver"
  ynh_support_level = "community"
