#!/bin/bash

app=vrchat-api
systemd_path=/etc/systemd/system/$app.service
final_path=/var/www/$app

# Stop and disable systemd service
systemctl stop $app
systemctl disable $app
rm -f $systemd_path

# Remove app files
rm -rf $final_path

# Reload systemd
systemctl daemon-reload
